name: Copy README to EC2

on:
  push:
    branches: [main]

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make README.md readable
        run: chmod 644 README.md || true

      - name: Copy README.md to EC2 (sanawarn folder)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "README.md"
          target: "~/sanawarn/"
          tar_mode: false
          timeout: 600s  # 10 minutes
          debug: true
