name: Deploy to EC2 via Docker Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, linux, ec2, docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp:latest ./api

      - name: Stop and remove existing container
        run: |
          docker stop myapp || true
          docker rm myapp || true

      - name: Run Docker container
        run: |
          docker run -d --name myapp -p 80:3000 myapp:latest
